### ISSUE TITLE
Synapse should handle multiple trackers better

### ISSUE THREAD

**Issue by whitequark** [Luminarys/synapse#100]
Currently, Synapse tries the first tracker and if that succeeds, does nothing else, whether there are any peers or not. At least, it should move to the next tracker if there are no peers. Transmission goes one step further and queries all trackers in parallel.

(Ref: https://github.com/Luminarys/synapse/issues/72#issuecomment-374812477)

**Comment by Luminarys** [comment]
Interestingly, [BEP 12](http://www.bittorrent.org/beps/bep_0012.html) seems to imply this behavior is correct (if the tracker can be reached then no more need to be tried), likely to help with load balancing for multi tracker torrents. Regardless, this should be addressed.

**Comment by whitequark** [comment]
In my case, the other peers are likely to be using different tracker lists that only partially overlap with mine due to the tracker lists in torrent files being subject to bitrot and consequently manual editing. I think there should be at least an option to poll all trackers.

**Comment by Luminarys** [comment]
Yea a manual option may be a better solution here.

**Comment by Luminarys** [comment]
I've implemented both described options.

**Comment by whitequark** [comment]
Thanks!
