### ISSUE TITLE
Hash checking too slow

### ISSUE THREAD

**Issue by armerpunkt** [Luminarys/synapse#102]
For testing synapse out, I added over 1500 torrents that I had been seeding in rtorrent.  It's been over 48 hours and it's still only about 75% complete.  I understand it takes a while to hash all this data, but it's not using my full CPU or disk speeds.  When rtorrent checks a hash, it does use the full disk speed (though I haven't done a comprehensive test to see how long it would take to recheck all these files at once in rtorrent).  So you might want to look at optimizing this functionality.  

However, an alternative would be to support rtorrent's fast resume torrents to avoid checking the hash altogether.  These add a "libtorrent_resume" object and a "rtorrent" object to the original torrent file.  I can provide example files for this if you are interested or you can download the script from here to create your own: https://github.com/rakshasa/rtorrent/blob/master/doc/rtorrent_fast_resume.pl (this would also make it really easy to write an rtorrent to synapse migration script)

**Comment by Luminarys** [comment]
The way disk jobs are scheduled right now is definitely sub-optimal in this sort of situation, I'll look into improving it.

**Comment by Luminarys** [comment]
As for migration, I think adding functionality to sycli to support this would be a good idea and will likely be pursued for this, or the next release.

**Comment by minus7** [comment]
Supporting rtorrent fastresumes seems to provide no benefit over adding torrents with a flag that says that the files should be assumed to be complete and do not have to be hashed.

**Comment by Luminarys** [comment]
I'm not sure you'd always want to completely trust the users in this sort of situation. Perhaps using such a flag would sample a small number random pieces in the torrent, and then mark the whole thing as valid if that succeeds.

**Comment by armerpunkt** [comment]
> Supporting rtorrent fastresumes seems to provide no benefit over adding torrents with a flag that says that the files should be assumed to be complete and do not have to be hashed.

The reason I suggested using rtorrent's fast resume is because it's a feature/functionality that has already been designed and proven to work.  Starting from scratch means there's a lot of design decisions to be made for how to best implement it before you can even start implementing it.  Why reinvent the wheel coming up with a way to safely fast resume?

**Comment by Luminarys** [comment]
I haven't read through the script you linked (I don't know perl), but is it safe to assume it generates some metadata for rtorrent/libtorrent which marks its pieces as validated? If so I'm not sure about starting from scratch, but what I have in mind for a migration process is parsing these sorts of files and converting them into synapse metadata, and the feature described above for pre-validation.

**Comment by armerpunkt** [comment]
I'm not a perl expert, but from my limited knowledge, it does some simple validation for each file in the torrent based on the file size and piece size to get the number of chunks and adds metadata for each file with the number of chunks found.  So if you're missing one file from a torrent that you're trying to add, it can still skip the hash on the other files you do have and it will perform a hash check on any files you do have that don't pass it's validation.

**Comment by Luminarys** [comment]
I've done some testing:
When hashing alone is done, performance is 80-85% that of the openssl tool. Any remaining gains could likely come from multithreaded hashing(which I don't plan on implementing for now).

However, to address this overall issue a new `import` flag has been added to the RPC and sycli to allow for importing already existing torrents. Please feel free to give further feedback in another issue if you encounter any other related issues.
