### ISSUE TITLE
Failed to query tracker http://sukebei.tracker.wf:8888/announce

### ISSUE THREAD

**Issue by RunningDroid** [Luminarys/synapse#117]
If I add any torrent from [sukebei.nyaa.si](https://sukebei.nyaa.si) Synapse prints `[synapse::torrent:573] E: Failed to query tracker http://sukebei.tracker.wf:8888/announce: invalid tracker response: Invalid BEncoded response!` and never finds peers for the torrent. The same torrents work fine in rtorrent.

**Comment by Luminarys** [comment]
After some troubleshooting, I think the response given by sukebei are invalid. They seem to contain an extra "peers6" key/value following the termination of the primary dictionary. Synapse's bencode implementation is strict, and thus rejects the message. I recommend reporting this to nyaa to have them fix the issue.

**Comment by Arylide** [comment]
Probably fixed now, none of us use this client though so you'll need to test it on your end.

**Comment by Luminarys** [comment]
Looks like it works now
