### ISSUE TITLE
Unable to compile sycli without nightly

### ISSUE THREAD

**Issue by wkpatrick** [Luminarys/synapse#119]
`lynx@debian:~/synapse$ cargo install --path ./sycli/
  Installing sycli v0.1.0 (file:///home/lynx/synapse/sycli)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling tokio-core v0.1.11
   Compiling phf_codegen v0.7.22
   Compiling websocket v0.20.2
   Compiling mime_guess v2.0.0-alpha.6
error[E0599]: no method named `accept_std` found for type `&mio::net::TcpListener` in the current scope
   --> /home/lynx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.11/src/net/tcp.rs:120:33
    |
120 |         match self.io.get_ref().accept_std() {
    |                                 ^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `tokio-core`.
warning: build failed, waiting for other jobs to finish...
`

I couldn't find anything involving this error and tokio. Please let me know if I can give any more info to help.

**Comment by Luminarys** [comment]
Are you sure your repo is up to date? I can't reproduce this on a fresh build.

**Comment by wkpatrick** [comment]
Up to date rustc, up  to date version of the repo. As far as I can tell, I should be good to go. 
[If somehow a picture can provide more info.](https://i.imgur.com/Gf3du27.png)

**Comment by wkpatrick** [comment]
You have to use rust nightly to compile. Thats what got me.

**Comment by Luminarys** [comment]
Ok after cleaning and updating I was able to reprod this. Having to use nightly is 100% a bug, synapse and associated tools will always target a stable version of rust.
