### ISSUE TITLE
Filter by tracker status

### ISSUE THREAD

**Issue by ddevault** [Luminarys/synapse#125]
Could be used to find torrents that have been pruned by the tracker.

**Comment by Luminarys** [comment]
This type of indirect query seems a bit less trivial to do, i.e. does the user want torrents where one tracker has status X, or all trackers?. Implementing this to support both may make sense to generally allow for querying the resource hierarchy which originates from torrents, i.e. allow querying `trackers.status == error` with an additional field indicating that the array match should be over has/notHas.

**Comment by Luminarys** [comment]
After some short discussion i think the simplest way of doing this is to allow querying subresources and defaulting to an implicit "there exists" when doing so.

Essentially we will expose in the torrent resource the fields `trackers, peers, files` and allow them to be queried like normal fields, but return all torrents which have at least one subresource satisfying the condition.

**Comment by Luminarys** [comment]
Done. This can be queried with `tracker/error:` now.

**Comment by ddevault** [comment]
Thanks!
