### ISSUE TITLE
Timeout to udp://tracker.archlinux.org:6969

### ISSUE THREAD

**Issue by tmplt** [Luminarys/synapse#126]
Using the following magnet link (official torrent for Arch Linux ISO) leads to a tracker timeout. The link works with aria2c(1).
```
magnet:?xt=urn:btih:b674f2afa42d2b72b5d5dbb6965d23edaebb2364&dn=archlinux-2018.10.01-x86_64.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce
```

**Comment by Luminarys** [comment]
Behavior seems to be repeatable for me, I'll look into it.

**Comment by Luminarys** [comment]
I can't seem to get the UDP tracker to work on qB, so I think Arch's UDP tracker may just be busted. I think it's quite possible that aria uses DHT to contact the tracker here.
