### ISSUE TITLE
How to put node in seed mode

### ISSUE THREAD

**Issue by zonque** [Luminarys/synapse#128]
For testing purposes, I've assembled a simple torrent file with only one file in it. This file is located in the folder pointed to by the `directory` directive in the config file. When I add this torrent using `sycli`, it is reported as 0% by `sycli list`. Shouldn't synapse detect is has all content for that torrent and report it as 100% available?

The other question I have may be related to this: How can I point a synapse node on a different node to the master seed to make it start downloading? Which port should be used in the `bootstrap_node` config setting? Is there any other component that's missing to make this work?

**Comment by Luminarys** [comment]
In theory synapse will do an initial hash of files for torrents when added. Are you sure that the torrent and data you're testing with are correct (i.e. they work for other clients as well). I'll verify this behavior on my own regardless.

bootstrap_node should accept any valid URL with a port which is an actual DHT node. Your question seems to imply you're talking about downloading though, in which case the boostrap_node serves a different purpose. If you want to manually connect a synapse node to another client to download a torrent, see the "ADD_PEER" command in the RPC spec.

**Comment by zonque** [comment]
> In theory synapse will do an initial hash of files for torrents when added. Are you sure that the torrent and data you're testing with are correct (i.e. they work for other clients as well). I'll verify this behavior on my own regardless.

You're right. I tried to make one with another torrent client and synapse now reports 100%. Great!

> bootstrap_node should accept any valid URL with a port which is an actual DHT node.

The address specified in the example config uses port 6881. Which of synapse's components is supposed to listen on that port? IOW, if I want to use two synapse instances that talk to each other, could I use port 16493 in the `bootstrap_node` setting?

> Your question seems to imply you're talking about downloading though, in which case the boostrap_node serves a different purpose.

Well, I want to get the file pieces from any node that has them. My understanding was that I need a bootstrap node to become part of the DHT network. 

> If you want to manually connect a synapse node to another client to download a torrent, see the "ADD_PEER" command in the RPC spec.

I tried that too, but the progress is stuck at 0.10% for a torrent containing a single file of about 32MB. Not sure what's going on.

**Comment by Luminarys** [comment]
If you want to connect two synapse instances via DHT, you'll want to use 16309 as your bootstrap node port (or whatever you configure the dht.port setting to).

I've done tests with ADD_PEER which appeared to work, but it's possible there's been a regression.

I can definitely say that the DHT code as a whole is flaky and very likely not totally correct, as is the piece picking code in certain situations. If you're able to provide some example torrent files I can try experimenting with them, otherwise I'll do some validation on my own.
