### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by ctlaltdefeat** [Luminarys/synapse#129]
Is this project still being actively pursued?

**Comment by Luminarys** [comment]
Basically the current status is that it works well enough in the context I need it to, so in conjunction with me being busy I'm not super active about developing new features.

That being said there's still things I want to improve in the longer term and I'm still paying attention to bug reports etc, so I guess you could say it's in a form of maintenance mode/hiatus for the time being.

**Comment by DavidNielsen** [comment]
Related, the website (https://synapse-bt.org) seems to be down.

**Comment by ddevault** [comment]
Looks up to me.

**Comment by armerpunkt** [comment]
@Luminarys It would be nice if you could do an official 1.0 release.  A lot of private trackers won't approve beta releases.

**Comment by Luminarys** [comment]
At this point I'm in the final parts of getting ready for an official release. I ultimately think I'm going to label it as 0.1 because there's still enough issues that I don't want to create a false impression of the maturity, but it should be quite soon now.

**Comment by Luminarys** [comment]
I think the client is stable enough to be called 1.0 now, but it definitely still has issues that will need eventual fixing. As I said in my initial response I don't think development will happen at a particularly fast speed but I do plan on maintaining and improving things gradually.
