### ISSUE TITLE
Move file downloading to special URL

### ISSUE THREAD

**Issue by Luminarys** [Luminarys/synapse#13]
Using DOWNLOAD_FILE and OPEN_TRANSFER is cumbersome, the DOWNLOAD_FILE command should be removed and a custom route used to download files using their ID + the password.

**Comment by Luminarys** [comment]
Implemented with a147afe69d464595cff06142524ec433ba553c6c.
The new download route is `/dl?password=hackme&id=ABCDEFG`.
Similarly to upgrading, password is only required if auth is turned on.

**Comment by ddevault** [comment]
:-1: to `/dl?id=:id`

Prefer `/dl/:id`

**Comment by Luminarys** [comment]
Updated.
