### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by Corsten56** [Luminarys/synapse#130]
Hello.

I'm trying to install synapse-bt package, but getting this:

> sudo apt-get install synapse-bt
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package synapse-bt

Using this https://github.com/Luminarys/synapse/wiki/Third-party-packages
Ubuntu 16.04.6

**Comment by Luminarys** [comment]
Did you follow all previous instructions for importing the repo? I just did a quick test of this and it seems to work on xenial.

**Comment by Corsten56** [comment]
Yes, all added.

Now I've fixed it, but got another problem.

> sudo apt-get install synapse-bt
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  synapse-bt : Depends: libgcc1 (>= 1:6.3.0) but 1:6.0.1-0ubuntu1 is to be installed
>               Depends: libc6 (>= 2.24) but 2.23-0ubuntu11 is to be installed
>               Depends: libssl1.1 (>= 1.1.0f) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> root@:~# apt-get install libgcc1
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libgcc1 is already the newest version (1:6.0.1-0ubuntu1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> root@:~# apt-get install libc6
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libc6 is already the newest version (2.23-0ubuntu11).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> root@:~# apt-get install libssl1.1
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package libssl1.1 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> E: Package 'libssl1.1' has no installation candidate

**Comment by Luminarys** [comment]
Yea it is admittedly packaged for Debian not Ubuntu. I'd recommend you either compile from source, or use the static binaries included in https://github.com/Luminarys/synapse/releases.

**Comment by Corsten56** [comment]
Ok, thanks. Will try binaries.
