### ISSUE TITLE
Disk job failed: couldn't stat fs

### ISSUE THREAD

**Issue by Corsten56** [Luminarys/synapse#131]
Ok, I'm trying binary executables on Ubuntu 16.04 VPS.

> 03/22/19 15:35:02 [synapse::init:24] I: Initializing
> 03/22/19 15:35:02 [synapse::config:176] I: Using default config
> 03/22/19 15:35:02 [synapse:111] I: Initialized, starting!
> 03/22/19 15:35:02 [synapse::rpc::processor:91] I: user data could not be read from disk, creating a fresh version: No such file or directory (os error 2)
> 03/22/19 15:35:02 [synapse::rpc:602] I: RPC SSL parameters not specified, using insecure connections!
> 03/22/19 15:35:02 [synapse::tracker::dht:49] I: DHT table could not be read from disk, creating new table!
> 03/22/19 15:35:02 [synapse::tracker::dht:53] I: Attempting DHT bootstrap!
> 03/22/19 15:35:02 [synapse::control:190] E: No server data found, regenerating!
> 03/22/19 15:35:12 [synapse::disk:132] E: Disk job failed: couldn't stat fs
> 03/22/19 15:35:22 [synapse::disk:132] E: Disk job failed: couldn't stat fs
> 03/22/19 15:35:32 [synapse::disk:132] E: Disk job failed: couldn't stat fs
etc, and so on..

What's it can be?

**Comment by Luminarys** [comment]
That disk job only exists to provide information on remaining space, so I wouldn't worry too much about the failure. That being said, what file system is your VPS using?
