### ISSUE TITLE
Listener thread panicked at "not yet implemented"

### ISSUE THREAD

**Issue by markpash** [Luminarys/synapse#132]
Hi,
I was running synapse 1.0-rc2 and now the current master and have experienced the same crash on both.
I leave synapse open for a day or two seeding Linux distribution ISOs and eventually it crashes on the unimplemented part of `handle_conn()` in `listener.rs`.

I am currently running this behind NAT and have forwarded all the necessary ports.
Please let me know if there is any further information you need.

**Comment by Luminarys** [comment]
I think this is just my bad, somehow a rare error condition in accepting a client condition isn't being handled.

**Comment by Luminarys** [comment]
The issue should be fixed now, though you'll have to compile from the latest source.
