### ISSUE TITLE
Announce request strip url query/queries?

### ISSUE THREAD

**Issue by ghost** [Luminarys/synapse#136]
I see that there are urls like `tracker.com/announce.php?passkey=PASS` or even `tracker.com/?h=PASS&`
Seems like in that case query should be appended to [http_req](https://github.com/Luminarys/synapse/blob/HEAD@%7B2019-06-04T12:15:11Z%7D/src/tracker/http/mod.rs#L346)

**Comment by Luminarys** [comment]
All private trackers I'm aware of encode their passkey into the URL path, but I guess this could be plausible since the spec doesn't specify anything about the details of the announce URL. I'll look into tweaking it.

**Comment by Luminarys** [comment]
Fixed.

**Comment by ghost** [comment]
Thank you!
