### ISSUE TITLE
Means of removing a torrent and its files via RPC

### ISSUE THREAD

**Issue by ddevault** [Luminarys/synapse#15]
Perhaps add an "artifacts" boolean to the `REMOVE_RESOURCE` request?

**Comment by Luminarys** [comment]
As in actually deleting the files on disk?

**Comment by ddevault** [comment]
Aye.

**Comment by ddevault** [comment]
Come to think of it, what should the behavior be if I `REMOVE_RESOURCE` for a file resource?

**Comment by Luminarys** [comment]
As of right now you'll get an error.
