### ISSUE TITLE
What is the project name correct spelling?

### ISSUE THREAD

**Issue by alexherbo2** [Luminarys/synapse#151]
It is written “synapse” or “Synapse”?

**Comment by ddevault** [comment]
If it's anything like my projects, the answer is "whatever you feel like at the time"

**Comment by alexherbo2** [comment]
I’ve only seen “receptor” occurrences in your project. :p

**Comment by alexherbo2** [comment]
I’ve got an answer from @ParadoxSpiral via IRC, and it is “synapse”, but either is ok.
