### ISSUE TITLE
File deletion does not work with sycli

### ISSUE THREAD

**Issue by aereaux** [Luminarys/synapse#172]
Right now, as far as I can tell, deleting a torrent and its files does not work with `sycli del <torrent> -f`.  Instead, the torrent is deleted from the synapse server, but the files remain in place.  It does, however, work if I use receptor to delete the torrent and files.

I tried to do some debugging, but I'm not too familiar with the synapse codebase, so my best guess was that it was because the sycli client immediately disconnects.

Let me know if you can't reproduce or need more info.

**Comment by Luminarys** [comment]
Looks like sycli isn't setting the artifacts flag when removing torrents, which is needed to delete the files as well. I'll look into adding an option to support this.

**Comment by aereaux** [comment]
Actually, that gave me the idea that I think is the issue.  There is already an option to do that, but it seems like it only works if you pass the string `true`, as in `sycli del archlinux-2020.02.01-x86_64.iso --files true`:
https://github.com/Luminarys/synapse/blob/b75eba955a2605ee9d92bf1a4880f6552593b883/sycli/src/main.rs#L409

It would probably make more sense if just the presence or absence of this option triggered it.
