### ISSUE TITLE
"size" field on magnets remains null until restart

### ISSUE THREAD

**Issue by steinuil** [Luminarys/synapse#174]
Steps to reproduce

- open RPC connection
- add a torrent from magnet link
- wait until all the magnet pieces have been downloaded
- close the connection
- open a new RPC connection
- get information on the torrent

**Expected:** the `size` field is not `null`
**Actual behavior:** the `size` field is `null`

It looks like the `size` field is sent only once when the pieces have been downloaded but after that it's not persisted, so any connection that happens after the magnet's pieces have been downloaded will receive `null` as `size`. After restarting synapse the size is reported correctly again.

**Comment by Luminarys** [comment]
Thanks for reporting, will look into this.

**Comment by Luminarys** [comment]
Should be fixed now
