### ISSUE TITLE
Status report / Roadmap

### ISSUE THREAD

**Issue by piperun** [Luminarys/synapse#189]
In the spirit of #78 & #1  I think it would be a better idea to make use of either external or Github's project tool as a way to showcase to people interested in the project how far/feature complete Synapse is and what is incomplete.

And if you want to be cheeky, you could always do a feature compare with other torrent clients.

**Comment by Luminarys** [comment]
Done. I think it'll take some time before I fully cover everything interesting but I'm starting to use the project to track development of some areas.
