### ISSUE TITLE
Can't build with LibreSSL 3.1

### ISSUE THREAD

**Issue by stacyharper** [Luminarys/synapse#191]
Hello there,

I'd like to package synapse for VoidLinux but I'm stuck on this error

```
--- stderr
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1 through 1.1.1, or LibreSSL 2.5
through 2.9.0, but a different version of OpenSSL was found. The build is now aborting
due to this version mismatch.

', /host/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.42/build/main.rs:238:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is there something I can do to allow the build for `libressl-devel-3.1.3_3` ?

Thanks a lot,
xoxo

**Comment by Luminarys** [comment]
I just checked the OpenSSL library and it doesn't look like any recent versions support libressl 3. I think this will likely make it difficult to package (though I don't know exactly how VoidLinux does its packaging). Given the recent security audit of RusTLS I'd like to eventually switch over which should solve this, but I'm not sure what the timeline will be around that.

**Comment by stacyharper** [comment]
Ok good ! We'll be patient then :) Thanks for all !
