### ISSUE TITLE
Ngrok doesn't work

### ISSUE THREAD

**Issue by iamtakingithard** [Luminarys/synapse#221]
Greetings, I am trying to get up myself an synapse.
I managed to up and run it, but when I try to connect to my instance via ngrok address on receptor. It tells me that I am disconnected.

**Comment by AndreVuillemot160** [comment]
For the note I use TCP address.

**Comment by AndreVuillemot160** [comment]
Nevermind, switcheed to Argo by Cloudflare and it worked.
