### ISSUE TITLE
Unable to get Ubuntu ISO

### ISSUE THREAD

**Issue by iamtakingithard** [Luminarys/synapse#222]
Greetings, I am trying to get Ubuntu ISO, I have tried both as magnet link and as .torrent file.
The trackers are writing this `Couldn't contact tracker: tracker IO error`

**Comment by Luminarys** [comment]
Given it's an Ubuntu ISO could you provide a link to the source? Alternatively could you provide the tracker URL?

**Comment by iamtakingithard** [comment]
The ironic thing, is that all trackers don't work.
And here is link https://releases.ubuntu.com/21.04/ubuntu-21.04-desktop-amd64.iso.torrent

**Comment by Luminarys** [comment]
This should be fixed now, it seems there was an "good" error we weren't handling in rustls.
