### ISSUE TITLE
Tracker: chunked encoding?

### ISSUE THREAD

**Issue by mayli** [Luminarys/synapse#226]
There are few trackers using chunked encoding and the chunk length is treated as part of body and causing bdecode failure. Any plan to support it?

Alternatively, the tracker client should report itself as `http/1.0` to avoid handling the chunked encoding.

**Comment by Luminarys** [comment]
If you're able I'd be happy to accept a change which reports our HTTP client as 1.0 to trackers. Not sure if there's any unintended potential side effects there. I think in theory we ought to use httparse to properly parse out chunks though.

**Comment by Luminarys** [comment]
Oh I totally missed your patch. Thanks!

**Comment by marieell** [comment]
This was fixed in bae263b1ab00b83b9c25f5f2f72cf3574ab23fb8 and can be closed now :)
