### ISSUE TITLE
Add arbitrary user data to resources

### ISSUE THREAD

**Issue by ddevault** [Luminarys/synapse#31]
There should be a dict on every resource that clients can just put anything they want in and have it persist.

**Comment by Luminarys** [comment]
What particular use case(s) do you have in mind for this?

**Comment by ddevault** [comment]
Letting clients add arbitrary shit without having to burden synapse with features. One idea I had was labelling torrents like you label github issues in receptor, for example. Another might be "pinning" particular torrents to the top of the list.

**Comment by ddevault** [comment]
Another use case: imagine an external daemon that read RSS feeds and added the torrents to synapse. It could add a field indicating that the torrent was automatically added and some information about the feed, which other clients could recognize and display in their UIs. Interop between RPC clients!
