### ISSUE TITLE
Edit FILTER_SUBSCRIBE after creation

### ISSUE THREAD

**Issue by ddevault** [Luminarys/synapse#39]
Feature request: submitting a FILTER_SUBSCRIBE with the same serial as an existing subscription should do a diff between the filters and issue RESOURCES_REMOVED and/or RESOURCES_EXTANT as appropriate.

I can probably do this on my end but it would be very complicated. Up for discussion.

**Comment by Luminarys** [comment]
What's the advantage of adding this over having clients just unsubscribe and resubscribe?

**Comment by ddevault** [comment]
At least in my UI, if I unsubscribe and all of those resources are removed, they'll disappear from the UI, then reappear with the new subscription. Seeing as I want to show search results live as you type, this is going to be ugly unless I employ hacks to avoid it.

**Comment by Luminarys** [comment]
Perhaps instead of using FILTER_SUBSCRIBE as a dual purpose search/subscribe, a new command should be made for explicitly searching which just returns RESOURCES_EXTANT.

**Comment by ddevault** [comment]
That doesn't make sense. I actually want to subscribe.

**Comment by Luminarys** [comment]
oh, misunderstood what you were saying. This shouldn't be too bad to do on the server end.
