### ISSUE TITLE
sycli features

### ISSUE THREAD

**Issue by ddevault** [Luminarys/synapse#6]
* [x] `sycli status` (server status)
* [x] `sycli get [id]`
* [x] `sycli watch [id]`
* [x] `sycli watch -c [id]` poll until complete (only applies to torrents)
* [x] `sycli torrent [id] tracker {add,remove} [...]`
* [x] `sycli torrent [id] peer {add, remove} [...]`
* [x] `sycli torrent [id] priority [num]`
* [x] `sycli torrent [id] {files, peers, trackers}`
* [x] `sycli file [id] priority [num]`

**Comment by ddevault** [comment]
Updated with a bunch of feature requests in one

**Comment by Luminarys** [comment]
Some quick notes:
- what would the semantics of the `get` command be? Just a dump of the resource data?
- would it not make sense for file priority to be a subcommand or flag for the torrent command?
- what does the `torrent [id] files` command do?

**Comment by ddevault** [comment]
>what would the semantics of the get command be? Just a dump of the resource data?

Pretty printed, ideally. For torrents it should also show tracker info and peers, perhaps?

>would it not make sense for file priority to be a subcommand or flag for the torrent command?

I want to associate top level commands with resource types.

>what does the torrent [id] files command do?

List files.

**Comment by Luminarys** [comment]
> List files.

In that case it probably makes sense to also add subcommands for peers/trackers as well.

> For torrents it should also show tracker info and peers, perhaps?

If subcommands like `torrent [id] {files, peers, trackers}` are offered this would probably be unnecessary.

**Comment by ddevault** [comment]
>If subcommands like torrent [id] {files, peers, trackers} are offered this would probably be unnecessary.

Sounds good to me.
