### ISSUE TITLE
Expose disk usage via server resource

### ISSUE THREAD

**Issue by ddevault** [Luminarys/synapse#65]

**Comment by ghost** [comment]
Isn't that a little out of scope for a torrent client?

**Comment by Luminarys** [comment]
It's useful enough to an end user that it's probably worth providing.

**Comment by ghost** [comment]
That's not really the question, and there are easy ways to do it already.

**Comment by ddevault** [comment]
Because Synapse is often going to be running on a seedbox, it's nice to know how your disk is doing from the client. Many other torrent clients do this, too.

**Comment by ghost** [comment]
I understand the use case, but it'll tickle the autism of some. I hope it'll
stop here and no CPU/IO meter gets added, haha.

**Comment by Luminarys** [comment]
Implemented.
