### ISSUE TITLE
Very large file sets

### ISSUE THREAD

**Issue by whitequark** [Luminarys/synapse#72]
Let's say I have a set of several hundreds of thousands of files that total dozens of terabytes across hundreds of torrent files, and I need to handle all of them simultaneously. rtorrent does start up but appears to hit some limits I could never identify and slow down for no apparent reason.

Do you think synapse could handle this task?

**Comment by ddevault** [comment]
It should work fine, and if it doesn't it's something we're interested in supporting. There's one particularly well known large torrent we've tested as a baseline which is >1.5T and >1000 files.

**Comment by whitequark** [comment]
TLMC, right? :)

Thanks. I will test and report, then.

**Comment by ddevault** [comment]
Oh, and we have a tool that simulates having lots of torrents with lots of files over RPC to make sure our RPC clients handle that well. Receptor seems to do pretty well.

**Comment by whitequark** [comment]
So I've been trying to actually test this case but it looks like Synapse is not connecting to any peers. With an identical torrent file (that I'm unfortunately unable to share) Transmission finds and connects to two peers.

How do I debug this? Does Synapse have, at least, some positive acknowledgement of receiving a peer list from a tracker?

**Comment by whitequark** [comment]
If I run `synapse -d` then I see the following in logs:
```
03/21/18 01:40:31 [synapse::torrent:1268] D: Starting torrent
03/21/18 01:40:31 [synapse::torrent:462] D: Sending serialization request!
03/21/18 01:40:31 [synapse::tracker:195] D: Handling announce request!
03/21/18 01:40:31 [synapse::tracker::udp:77] D: Received a new announce req for "udp://redacted:6969/announce"
03/21/18 01:40:31 [synapse::tracker::udp:100] D: Dispatching DNS req for 0, url: "redacted"
03/21/18 01:40:31 [synapse::control:135] D: Initialized!
03/21/18 01:40:31 [synapse::tracker::udp:108] D: Received a DNS resp for 0
03/21/18 01:40:32 [synapse::control:288] D: Handling tracker response for "udp://redacted:6969/announce"
03/21/18 01:40:32 [synapse::torrent:500] D: Processing tracker response
```
and then a sequence of
```
03/21/18 01:41:31 [synapse::torrent:559] D: Updating tracker at interval!
03/21/18 01:41:31 [synapse::control:155] D: Serializing server data!
03/21/18 01:41:31 [synapse::control:166] D: Serializing torrents!
03/21/18 01:41:31 [synapse::torrent:462] D: Sending serialization request!
```
According to Transmission at least, this tracker should return some peers. In any case there are several dozen more trackers for that torrent that should be polled too, I don't know why aren't they.

**Comment by Luminarys** [comment]
It's possible that the peers are using MSE/PE which synapse currently doesn't support. You are correct that synapse's multi tracker behavior is slightly off here, since if it finds no peers for a tracker it should move to the next one.

Additionally, DHT is a bit slow (needs some more work too) which won't help here.

**Comment by Luminarys** [comment]
Could you open a new issue instead?

**Comment by Luminarys** [comment]
Also, you can try manually triggering reannounces to the trackers which aren't being contacted. This probably should be supported in sycli but can be done in receptor.

**Comment by whitequark** [comment]
Manually triggered all reannounces; no change.
