### ISSUE TITLE
Improve efficiency at scale

### ISSUE THREAD

**Issue by Luminarys** [Luminarys/synapse#83]
There's numerous places where CPU is unnecessarily burned, mainly iterating through vectors to recompute things. This doesn't matter so much for your average torrent, but in certain situations this can be quite expensive. Performance should be audited and improved where needed for these cases.

**Comment by Luminarys** [comment]
While this is going to continue be an ongoing process, through testing the TLMC the vast majority of performance killers have been resolved. Given how generic this issue is I'm closing it for now and if future issues with performance arise they can be dealt with on a more specific basis.

**Comment by C84186** [comment]
I'm curious how this compares to the "famous" torrent clients - Transmission & qBittorrent in particular.

I'm finding that qBittorrent tends to suffer around >5000 (probably less, not sure) torrents, at least on the webUI. I don't know about transmission.
