### ISSUE TITLE
DNS Resolution

### ISSUE THREAD

**Issue by Luminarys** [Luminarys/synapse#91]
DNS resolution as it is now kinda sucks: we manually poll c-ares rather than doing actual async resolution, and have to deal with c-ares in the builds (this has not been a great experience so far).

Alternatives:
* Implement our own basic async DNS resolver
* Create a thread which does synchronous resolves

I don't particularly like the latter because it still blocks all progress on a bad resolve, so the former will likely be done using some existant DNS parsing crate.

**Comment by KyleSanderson** [comment]
When this lands please add a way to purge the cache. Stats are lost when trackers jump from IP to IP and the client never initiates a purge.

**Comment by valpackett** [comment]
What do you think about [trust-dns-resolver](https://crates.io/crates/trust-dns-resolver)?

**Comment by Luminarys** [comment]
The trust-dns project is impressive, however I don't think it'd be a good fit in synapse (which doesn't use tokio, nor do I plan on integrating it).

**Comment by Luminarys** [comment]
The approach taken with caching is to hold cache entries according to their TTL in memory. A forced purge can be initiated by restarting the client.

**Comment by KyleSanderson** [comment]
@Luminarys obviously any reasonable person would find restarting the client unacceptable?

**Comment by Luminarys** [comment]
I do agree that restarting the client is a bit cumbersome. I'll think about ways to add in cache purging in the meanwhile.

**Comment by dimbleby** [comment]
Hey, 

Maintainer of the `c-ares` bindings here.  Sorry to hear that dealing with c-ares in the builds was not a good experience for you.  Is there anything I can fix that would have helped?

(Not seeking to persuade you to switch back or anything, just keen for things to be as painless as possible for future users).

Also: I'd expected that people would generally prefer the [`c-ares-resolver`](https://crates.io/crates/c-ares-resolver) crate, which relieves you of the burden of manually polling c-ares.  I'd be interested to know, if you can remember, whether it was a deliberate decision to use `c-ares` directly?

Thanks!

**Comment by Luminarys** [comment]
Actually the c-ares bindings if anything were great, they made it very easy to use the library. The fundamental problem was with c-ares' design (having to poll an arbitrary fdset) interacting poorly with our event loop structure. The build issues were also all on the C end, not the c-ares crates, so I have no real complaints there either.

**Comment by dimbleby** [comment]
Thanks for the reply.

I'm a little surprised by your remark about interacting poorly with an event loop structure.  

I'd expect that for most people the main downside of `c-ares` would exactly be the requirement to work with a low-level event loop (which is what `c-ares-resolver` is intended to mitigate).  But if you already have an event loop, I'd have thought that `c-ares` should be a straightforward fit...

But I've not looked at your code too closely; I expect you're right!

Anyway, thanks again for the comments.
