### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by scoobynz** [Luminarys/synapse#94]
Hello,

Apologies if I'm missing something obvious. 
Installed Synapse on a debian server on my LAN. I think its working, but dont really know how to test it. I do get these messages but I'm trying to convince myself they are not important;
`03/10/18 17:05:18 [synapse::rpc::processor:90] I: user data could not be read from disk, creating a fresh version: No such file or directory (os error 2)
03/10/18 17:05:18 [synapse::rpc:603] E: Failed to load SSl certificate chain: error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:292:fopen('./cert.pem','r'), error:20074002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:294:, error:140DC002:SSL routines:use_certificate_chain_file:system lib:../ssl/ssl_rsa.c:609:
`
I have installed receptor on the LAN server, as per instructions. When I run it I get;
`Listening at http://localhost:3000
webpack built 566240d0b62ecebd579f in 22603ms
`
Which looks promising.

If I navigate to http://SERVERIP:3000 I get nothing. Are there any webserver (nginx) requirements, I'm assuming not as npm takes care of it all.

OK, so I tried using https://web.synapse-bt.org/
When I go to the page I fill in URI as either ws://SERVERIP:8412, I have also tried ws://mydomain.com:8412, with my domain and 8412 forwarded through the firewall.

All connects fail. Any suggestions / comments appreciated.

**Comment by ddevault** [comment]
Make sure you copy `example_config.toml` to `~/.config/synapse.toml` and make the following changes:

* Set `password` to something reasonable
* Set `auth` to true
* Set `local` to false

Then you should be able to go to http://web.synapse-bt.org and punch in `ws://serverip:8412` and your password.

**Comment by scoobynz** [comment]
Thanks for the assistance.

My setup is (now) as per your suggestion. When I try to connect it just gets a "Connecting" pop-up, but it doesnt connect. I've tried multiple browsers and have bypassed my proxy for the box in question.

I still have the same Synapse messages as above.

**Comment by Luminarys** [comment]
Can you try running synapse with the `-d` flag and looking at the log messages about incoming connections when you try to connect?

**Comment by scoobynz** [comment]
I was hunting around github trying to find out how to log . . . I'm a drrrr.

It looks OK, except for the same error about ssl
`03/10/18 19:33:39 [synapse::init:20] I: Initializing
03/10/18 19:33:39 [synapse::config:162] D: Failed to load config file ./config.toml: IO failed
03/10/18 19:33:39 [synapse::config:162] D: Failed to load config file $XDG_CONFIG_HOME/synapse.toml: bad env var
03/10/18 19:33:39 [synapse::config:173] I: Loaded config file
03/10/18 19:33:40 [synapse:104] I: Initialized, starting!
03/10/18 19:33:40 [synapse::tracker::dht::rt:102] I: Loaded 21 dht buckets, 165 nodes
03/10/18 19:33:40 [synapse::tracker::dht:53] I: Attempting DHT bootstrap!
03/10/18 19:33:40 [synapse::handle:38] D: listener thread started
03/10/18 19:33:40 [synapse::listener:72] D: Accepting connections!
03/10/18 19:33:40 [synapse::handle:38] D: disk thread started
03/10/18 19:33:40 [synapse::handle:38] D: rpc thread started
03/10/18 19:33:40 [synapse::rpc::processor:90] I: user data could not be read from disk, creating a fresh version: No such file or directory (os error 2)
03/10/18 19:33:40 [synapse::control:179] D: Deserializing server data!
03/10/18 19:33:40 [synapse::control:191] D: Deserializing torrents!
03/10/18 19:33:40 [synapse::control:140] D: Initialized!
03/10/18 19:33:40 [synapse::handle:38] D: trk thread started
03/10/18 19:33:40 [synapse::tracker::dht:71] D: Initializing DHT nodes!
03/10/18 19:33:40 [synapse::rpc:603] E: Failed to load SSl certificate chain: error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:292:fopen('./cert.pem','r'), error:20074002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:294:, error:140DC002:SSL routines:use_certificate_chain_file:system lib:../ssl/ssl_rsa.c:609:
03/10/18 19:33:40 [synapse::rpc:223] D: Running RPC!
03/10/18 19:33:40 [synapse::tracker:129] D: Initialized!
`

**Comment by Luminarys** [comment]
To confirm, after trying to connect in receptor, you saw no log output about incoming RPC connections

**Comment by scoobynz** [comment]
Thats correct. The log remains static

**Comment by Luminarys** [comment]
This implies the connections aren't even getting to synapse in the first place. Are you sure you've forwarded 8412 on your server?

**Comment by scoobynz** [comment]
Yeah, it feels like a blocked port. The server is a virtual machine, fresh debian install, so it doesnt have a firewall. I have a rule for another server that opens port 80 to the internet and I have copied that rule, so I think 8412 is open.
edit: Will look at this again tomorrow. Thanks for the help.

**Comment by scoobynz** [comment]
OK. I have opened the port - I'm kinda new to pfSense which was the issue. When I go to, for e.g. portchecker.co, and put in my WAN IP and port 8412 it says the port is open. Previously it said it was closed.

When I run the port check (from portchecker.co) with synapse -d running, I now see a response from synapse - which proves the port is open. The response at each port check request is;
`
03/11/18 13:19:26 [synapse::rpc:362] D: Accepted new connection from V4(45.33.50.110:36232)!
03/11/18 13:19:26 [synapse::rpc:462] D: Incoming ws upgrade failed: unexpected end of file
`
Progress. I can connect to http://web.synapse-bt.org/  BUT ONLY if I rewrite the url to explicitly make it http. https gives the same "Connecting . . ." as before. This fits in with the SSL error message above I suppose??

I tried downloading a linux distro, everything works well and it seems incredibly snappy / fast. I'm impressed.

Next. As much as I commend the work done on receptor which feels good upon limited use, my real interest was using the RPC translator with transmission. I have cloned broca from github. Does it need installation? How do you run / start it? I have tried running "python3 setup.py" but I see this needs further commands, but I am unsure what commands to use (build, install etc?) to get it up and running. Or would you prefer me to open a new thread on the broca github page?

Here is my offering of encouragement and thanks. It seems you are onto something here.

**Comment by ddevault** [comment]
Run `./broca-daemon`

If it doesn't work, then

>Or would you prefer me to open a new thread on the broca github page?

Do this
