### ISSUE TITLE
Failed to add torrents: Failed to receieve upload acknowledgement from synapse

### ISSUE THREAD

**Issue by whitequark** [Luminarys/synapse#98]
This message indicates a corrupted .torrent file, but is completely uninformative.

**Comment by ddevault** [comment]
That sounds reasonably informative to me. Your bug report, on the other hand, is not. How did you add the torrent? Do you have the torrent file?

**Comment by whitequark** [comment]
Oh sorry, I should've mentioned that I'm adding it with `sycli add`.
An example torrent file (or I guess not actually a torrent file) that triggers this:
```
<head><title>503 Service Temporarily Unavailable</title></head>
<center><h1>503 Service Temporarily Unavailable</h1></center>
```

**Comment by ddevault** [comment]
Then the error is exactly as it says. That's not a torrent file. That's an HTML 503 page.

**Comment by whitequark** [comment]
"Failed to receieve upload acknowledgement" can mean absolutely anything. Is it out of memory? Did it exhaust disk space? It didn't even occur to me that it has failed to parse the file until I compared the sizes.

How about printing a useful error message instead?

**Comment by ddevault** [comment]
Ah. I thought the error was "torrent is corrupt" or so from your original report.

**Comment by Luminarys** [comment]
The failed to receive acknowledgment error should definitely provide some more context.

**Comment by Luminarys** [comment]
This specific issue is fixed, but there's probably more situations where the error handling could be improved. Please open more issues if this is encountered.

**Comment by whitequark** [comment]
Thanks!
